### ISSUE TITLE
Не запускается по инструкции раздела "Как запускать"

### ISSUE THREAD

**Issue by Rishat-F** [avidale/python-ruwordnet#5]
Добрый вечер/день!
Следуя инструкции из раздела README "Как запускать" выдается ошибка. Какие-то проблемы с SQLAlchemy:

$ ruwordnet download

Traceback (most recent call last):
  File "/home/hacker/tmp/venv/bin/ruwordnet", line 33, in <module>
    sys.exit(load_entry_point('ruwordnet==0.0.5', 'console_scripts', 'ruwordnet')())
  File "/home/hacker/tmp/venv/bin/ruwordnet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/ruwordnet/__init__.py", line 1, in <module>
    from . import models, ruwordnet
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/ruwordnet/models.py", line 26, in <module>
    class Sense(Base):
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 199, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1005, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1233, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/hacker/tmp/venv/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2365, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "Sense.synset" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)

**Comment by Rishat-F** [comment]
Версия SQLAlchemy=2.0.5:

$ pip freeze
greenlet==2.0.2
ruwordnet==0.0.5
SQLAlchemy==2.0.5.post1
typing_extensions==4.5.0

Если использовать более старую версию SQLAlchemy (например, 1.4.11), то все запускается и работает.

**Comment by avidale** [comment]
Спасибо за замечания!
Катнул `ruwordnet==0.0.6` с ограничениями на версию sqlalchemy в requirements.
